#!/bin/bash

if [ "$#" == 0 ]; then
    echo -e "Usage:\nbrokensymlinks \${path}"
fi

brokensymlinks() {
    for name in "$@"; do
        if [[ -d "$name" && ! -L "$name" ]]; then
            brokensymlinks "$name"/*
        fi
		if [[ ! -e "$name"  && -L "$name" ]]; then
	    echo ${name}
        fi
    done
}

brokensymlinks "$@"
